# Site settings
title: Sivar Azadi
email: sivarmazadi@gmail.com
url: https://sivarazadi.github.io
description: "Recent Physics BS graduate from the University of California, Santa Barbara exploring data science or machine learning roles. "

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Sivar Azadi

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/Sivarazadi
  - title: linkedin
    url: https://www.linkedin.com/in/sivar-azadi/

# Build settings
markdown: kramdown
permalink: pretty
